
language: node_js 

node_js: 
  - "10.15.0" 

cache: 
  directories: 
    - "node_modules" 
    
addons: 
  postgresql: "9.5.15" 

services: 
  - postgresql 

before_install: 
  - psql -c "CREATE  DATABASE IF NOT EXISTS politico_db;" -U postgres
before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
    - psql -c "CREATE USER moise WITH PASSWORD 'mojaf123';" -U postgres

after_script:
    
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

script:
    - npm test

after_success:
    - npm run coveralls

