env: 
    global: 
        cc_test_result: CC_TEST_REPORTER

language: node_js 

node_js: 
  - "stable" 
cache: 
  directories: 
    - "node_modules" 

addons:
  code_climate: 
    repo_token:
      secure: REPO_TOKEN

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-netcgo-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

after_script:
    - coveralls < ./coverage/lcov.info
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

script:
    - npm test
after_success:
    - npm run coveralls

